function percentErrorTest = Q2c_hidden30()

% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 20-May-2020 20:25:44
%
% This script assumes these variables are defined:
%
%   StandardizedInputs - input data.
%   targets - target data.
load StandardizedInputs.mat;
load targets.mat;

x = StandardizedInputs';
t = targets';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 30;
net = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);
tind = round(t);
yind = round(y);
percentErrors = sum(tind ~= yind)/numel(tind);

% get the test index
testIndex = tr.testInd;
expected = t(testIndex);
actual = yind(testIndex);
percentErrorTest = sum(expected ~= actual)/47;

% View the Network
% view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

